# Generated by Django 4.2.3 on 2023-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(default=1, max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
