# Generated by Django 4.2.3 on 2023-07-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='slug',
        ),
    ]
