# Generated by Django 4.2.3 on 2023-07-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen_by',
        ),
    ]
